-- Create a new table to store structured territory checks
CREATE TABLE IF NOT EXISTS territory_checks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    franchise_id BIGINT NOT NULL REFERENCES "Franchises"(id) ON DELETE CASCADE,
    check_date TIMESTAMPTZ,
    location_raw TEXT,
    state_code VARCHAR(2),
    availability_status VARCHAR(50) CHECK (availability_status IN ('Available', 'Not Available', 'Pending')),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_territory_checks_franchise_id ON territory_checks(franchise_id);
CREATE INDEX IF NOT EXISTS idx_territory_checks_state_code ON territory_checks(state_code);
CREATE INDEX IF NOT EXISTS idx_territory_checks_availability_status ON territory_checks(availability_status);

-- Enable RLS (Row Level Security)
ALTER TABLE territory_checks ENABLE ROW LEVEL SECURITY;

-- Create a policy that allows read access to everyone (or authenticated users depending on your auth model)
-- Adjust this policy based on your actual security requirements
CREATE POLICY "Enable read access for all users" ON territory_checks FOR SELECT USING (true);

-- Create a policy that allows insert/update/delete for service role only (or authenticated users if needed)
-- For now, assuming backend service role manages this table
CREATE POLICY "Enable all access for service role" ON territory_checks USING (auth.role() = 'service_role') WITH CHECK (auth.role() = 'service_role');

