-- Create Leads table for persistent lead management
CREATE TABLE IF NOT EXISTS leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_name TEXT,
    notes TEXT,
    profile_data JSONB,
    matches JSONB,
    qualification_status VARCHAR(50) CHECK (qualification_status IN ('tier_1', 'tier_2')),
    workflow_status VARCHAR(50) DEFAULT 'new', -- e.g., 'new', 'analyzed', 'contacted', 'archived'
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for faster lookups
CREATE INDEX IF NOT EXISTS idx_leads_created_at ON leads(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_leads_workflow_status ON leads(workflow_status);
CREATE INDEX IF NOT EXISTS idx_leads_qualification_status ON leads(qualification_status);

-- Enable RLS (Row Level Security) - Best practice even if open for MVP
ALTER TABLE leads ENABLE ROW LEVEL SECURITY;

-- Policy: Allow all access (Adjust for production!)
CREATE POLICY "Enable all access for leads" ON leads FOR ALL USING (true) WITH CHECK (true);

-- Trigger for updated_at (Assumes update_updated_at_column function exists from previous migrations)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'update_leads_updated_at') THEN
        CREATE TRIGGER update_leads_updated_at
            BEFORE UPDATE ON leads
            FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
    END IF;
END
$$;

